"use client";

import { motion } from "framer-motion";

const quotes = [
  {
    name: "Mark Zuckerberg",
    title: "Meta CEO, 2025",
    quote:
      "Probably in 2025, we're going to have an AI that can effectively be a sort of mid-level engineer that you have at your company that can write code.",
    korean:
      "2025년이면 회사의 중급 엔지니어 수준으로 코드를 작성하는 AI가 등장할 것이다.",
    context: "Joe Rogan Podcast, 2025년 1월",
  },
  {
    name: "Sundar Pichai",
    title: "Google CEO, 2024",
    quote:
      "More than 25% of all new code at Google is now generated by AI.",
    korean:
      "구글의 신규 코드 중 25% 이상이 이미 AI가 작성하고 있다.",
    context: "2024 Q3 Earnings Call",
  },
  {
    name: "Andrej Karpathy",
    title: "2025",
    quote:
      "It's like some powerful alien tool has been thrown into the world without an instruction manual. This magnitude 9 career earthquake has already shaken the entire industry.",
    korean:
      "설명서 없이 강력한 외계 도구가 세상에 던져진 것과 같다. 규모 9의 커리어 지진이 이미 산업 전체를 흔들고 있다.",
    context: "2025년 말 회고",
  },
  {
    name: "Jensen Huang",
    title: "NVIDIA CEO, 2024",
    quote:
      "AI won't replace humans, but humans with AI will replace humans without AI.",
    korean:
      "AI가 인간을 대체하는 것이 아니라, AI를 사용하는 인간이 AI를 사용하지 않는 인간을 대체할 것이다.",
    context: "다양한 인터뷰에서 반복",
  },
];

export default function TechLeadersOnAI() {
  return (
    <section className="relative bg-slate-900 py-24 px-6 text-white overflow-hidden">
      {/* Section Header */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6 }}
        className="max-w-5xl mx-auto text-center mb-16"
      >
        <span className="inline-block px-4 py-1.5 rounded-full bg-violet-500/10 border border-violet-500/20 text-violet-400 text-sm font-medium mb-6">
          Industry Voices
        </span>
        <h2 className="text-3xl md:text-4xl font-bold">
          테크 리더들이 말하는 AI 시대
        </h2>
      </motion.div>

      {/* Karpathy Original Tweet Card */}
      <motion.div
        initial={{ opacity: 0, y: 40 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.7, delay: 0.1 }}
        className="max-w-4xl mx-auto mb-16"
      >
        <div className="relative rounded-2xl p-[1px] bg-gradient-to-r from-violet-500 to-fuchsia-500">
          <div className="rounded-2xl bg-slate-900 p-8 md:p-10">
            <h3 className="text-2xl font-bold mb-1">
              바이브코딩의 탄생
            </h3>
            <p className="text-gray-400 text-sm mb-6">
              Andrej Karpathy &middot; 2025년 2월 6일 &middot; X (Twitter)
            </p>

            <blockquote className="border-l-4 border-violet-500 pl-5 mb-6 text-gray-300 italic leading-relaxed">
              &ldquo;There&apos;s a new kind of coding I call &apos;vibe
              coding&apos;, where you fully give in to the vibes, embrace
              exponentials, and forget that the code even exists. It&apos;s
              possible because the LLMs (e.g. Cursor Composer w Sonnet) are
              getting too good. Also I just talk to Composer with SuperWhisper
              so I barely even touch the keyboard. I ask for the dumbest things
              like &apos;decrease the padding on the sidebar by half&apos;
              because I&apos;m too lazy to find it. I &apos;Accept All&apos;
              always, I don&apos;t read the diffs anymore. When I get error
              messages I just copy paste them in with no comment, usually that
              fixes it. The code grows beyond my usual comprehension, I&apos;d
              have to really read through it for a while. Sometimes the LLMs
              can&apos;t fix a bug so I just work around it or ask for random
              changes until it goes away. It&apos;s not too bad for throwaway
              weekend projects, but still quite amusing.&rdquo;
            </blockquote>

            <p className="text-gray-400 leading-relaxed mb-6">
              코드를 직접 읽지도, 수정하지도 않는다. 에러가 나면 복사해서
              붙여넣기만 한다. 코드가 이해 범위를 넘어서지만, 그래도 작동한다.
              아직 주말 프로젝트 수준이지만, 꽤 재미있다.
            </p>

            <p className="text-sm text-fuchsia-400 font-medium">
              이 트윗 하나가 4백만 뷰를 기록하며 &apos;바이브코딩&apos;이라는
              용어를 탄생시켰다.
            </p>
          </div>
        </div>
      </motion.div>

      {/* Quotes Grid */}
      <div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-6 mb-16">
        {quotes.map((q, i) => (
          <motion.div
            key={q.name + i}
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.1 * i }}
            className="rounded-2xl bg-slate-800/50 border border-slate-700 p-6"
          >
            <div className="mb-4">
              <span className="font-bold text-white">{q.name}</span>
              <span className="ml-2 text-sm text-gray-400">{q.title}</span>
            </div>
            <p className="italic text-gray-300 leading-relaxed mb-3">
              &ldquo;{q.quote}&rdquo;
            </p>
            <p className="text-gray-400 text-sm leading-relaxed mb-4">
              {q.korean}
            </p>
            <p className="text-xs text-gray-500">{q.context}</p>
          </motion.div>
        ))}
      </div>

      {/* Bottom Insight */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6, delay: 0.2 }}
        className="max-w-3xl mx-auto text-center"
      >
        <p className="text-lg md:text-xl text-gray-300 leading-relaxed">
          이 수업을 듣는 여러분은 이미 한 발 앞서 있습니다.
          <br />
          <span className="text-white font-semibold">
            기계공학 도메인 지식 + AI 활용 능력 = 대체 불가능한 엔지니어
          </span>
        </p>
      </motion.div>
    </section>
  );
}
